// Podcast Categories
function get_podcast_categories(){
	return array(
		'' => __('Select a category'),
		'Arts' => __('Arts'),
		'Arts > Books' => __('Arts > Books'),
		'Arts > Design' => __('Arts > Design'),
		'Arts > Fashion & Beauty' => __('Arts > Fashion & Beauty'),
		'Arts > Food' => __('Arts > Food'),
		'Arts > Performing Arts' => __('Arts > Performing Arts'),
		'Arts > Visual Arts' => __('Arts > Visual Arts'),

		'Business' => __('Business'),
		'Business > Careers' => __('Business > Careers'),
		'Business > Entrepreneurship' => __('Business > Entrepreneurship'),
		'Business > Investing' => __('Business > Investing'),
		'Business > Management' => __('Business > Management'),
		'Business > Marketing' => __('Business > Marketing'),
		'Business > Non-Profit' => __('Business > Non-Profit'),

		'Comedy' => __('Comedy'),
		'Comedy > Comedy Interviews' => __('Comedy > Comedy Interviews'),
		'Comedy > Improv' => __('Comedy > Improv'),
		'Comedy > Stand-Up' => __('Comedy > Stand-Up'),

		'Education' => __('Education'),
		'Education > Courses' => __('Education > Courses'),
		'Education > How To' => __('Education > How To'),
		'Education > Language Learning' => __('Education > Language Learning'),
		'Education > Self-Improvement' => __('Education > Self-Improvement'),

		'Fiction' => __('Fiction'),
		'Fiction > Comedy Fiction' => __('Fiction > Comedy Fiction'),
		'Fiction > Drama' => __('Fiction > Drama'),
		'Fiction > Science Fiction' => __('Fiction > Science Fiction'),

		'Government' => __('Government'),

		'History' => __('History'),

		'Health & Fitness' => __('Health & Fitness'),
		'Health & Fitness > Alternative Health' => __('Health & Fitness > Alternative Health'),
		'Health & Fitness > Fitness' => __('Health & Fitness > Fitness'),
		'Health & Fitness > Medicine' => __('Health & Fitness > Medicine'),
		'Health & Fitness > Mental Health' => __('Health & Fitness > Mental Health'),
		'Health & Fitness > Nutrition' => __('Health & Fitness > Nutrition'),
		'Health & Fitness > Sexuality' => __('Health & Fitness > Sexuality'),

		'Kids & Family' => __('Kids & Family'),
		'Kids & Family > Education for Kids' => __('Kids & Family > Education for Kids'),
		'Kids & Family > Parenting' => __('Kids & Family > Parenting'),
		'Kids & Family > Pets & Animals' => __('Kids & Family > Pets & Animals'),
		'Kids & Family > Stories for Kids' => __('Kids & Family > Stories for Kids'),

		'Leisure' => __('Leisure'),
		'Leisure > Animation & Manga' => __('Leisure > Animation & Manga'),
		'Leisure > Automotive' => __('Leisure > Automotive'),
		'Leisure > Aviation' => __('Leisure > Aviation'),
		'Leisure > Crafts' => __('Leisure > Crafts'),
		'Leisure > Games' => __('Leisure > Games'),
		'Leisure > Hobbies' => __('Leisure > Hobbies'),
		'Leisure > Home & Garden' => __('Leisure > Home & Garden'),
		'Leisure > Video Games' => __('Leisure > Video Games'),

		'Music' => __('Music'),
		'Music > Music Commentary' => __('Music > Music Commentary'),
		'Music > Music History' => __('Music > Music History'),
		'Music > Music Interviews' => __('Music > Music Interviews'),

		'News' => __('News'),
		'News > Business News' => __('News > Business News'),
		'News > Daily News' => __('News > Daily News'),
		'News > Entertainment News' => __('News > Entertainment News'),
		'News > News Commentary' => __('News > News Commentary'),
		'News > Politics' => __('News > Politics'),
		'News > Sports News' => __('News > Sports News'),
		'News > Tech News' => __('News > Tech News'),

		'Religion & Spirituality' => __('Religion & Spirituality'),
		'Religion & Spirituality > Buddhism' => __('Religion & Spirituality > Buddhism'),
		'Religion & Spirituality > Christianity' => __('Religion & Spirituality > Christianity'),
		'Religion & Spirituality > Hinduism' => __('Religion & Spirituality > Hinduism'),
		'Religion & Spirituality > Islam' => __('Religion & Spirituality > Islam'),
		'Religion & Spirituality > Judaism' => __('Religion & Spirituality > Judaism'),
		'Religion & Spirituality > Religion' => __('Religion & Spirituality > Religion'),
		'Religion & Spirituality > Spirituality' => __('Religion & Spirituality > Spirituality'),

		'Society & Culture' => __('Society & Culture'),
		'Society & Culture > Documentary' => __('Society & Culture > Documentary'),
		'Society & Culture > Personal Journals' => __('Society & Culture > Personal Journals'),
		'Society & Culture > Philosophy' => __('Society & Culture > Philosophy'),
		'Society & Culture > Places & Travel' => __('Society & Culture > Places & Travel'),
		'Society & Culture > Relationships' => __('Society & Culture > Relationships'),

		'Sports' => __('Sports'),
		'Sports > Baseball' => __('Sports > Baseball'),
		'Sports > Basketball' => __('Sports > Basketball'),
		'Sports > Cricket' => __('Sports > Cricket'),
		'Sports > Fantasy Sports' => __('Sports > Fantasy Sports'),
		'Sports > Football' => __('Sports > Football'),
		'Sports > Golf' => __('Sports > Golf'),
		'Sports > Hockey' => __('Sports > Hockey'),
		'Sports > Rugby' => __('Sports > Rugby'),
		'Sports > Running' => __('Sports > Running'),
		'Sports > Soccer' => __('Sports > Soccer'),
		'Sports > Swimming' => __('Sports > Swimming'),
		'Sports > Tennis' => __('Sports > Tennis'),
		'Sports > Volleyball' => __('Sports > Volleyball'),
		'Sports > Wilderness' => __('Sports > Wilderness'),
		'Sports > Wrestling' => __('Sports > Wrestling'),

		'Technology' => __('Technology'),

		'True Crime' => __('True Crime'),

		'TV & Film' => __('TV & Film'),
		'TV & Film > After Shows' => __('TV & Film > After Shows'),
		'TV & Film > Film History' => __('TV & Film > Film History'),
		'TV & Film > Film Interviews' => __('TV & Film > Film Interviews'),
		'TV & Film > Film Reviews' => __('TV & Film > Film Reviews'),
		'TV & Film > TV Reviews' => __('TV & Film > TV Reviews'),
	);
}